
package main;

/**
 *
 * @author Migue
 */
public class jdGuardarPlaylist extends javax.swing.JDialog {
    
    int DECISION;
    boolean haPulsadoAceptar;

    /**
     * Creates new form jdGuardarPlaylist
     */
    public jdGuardarPlaylist(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jbAceptar.setVisible(false);
        jbCancelar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTexto = new javax.swing.JLabel();
        jbM3U = new javax.swing.JButton();
        jbPLS = new javax.swing.JButton();
        jbXPFS = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlTexto.setText("¿En que formato desea guardar la playlist?");

        jbM3U.setText("M3U");
        jbM3U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbM3UActionPerformed(evt);
            }
        });

        jbPLS.setText("PLS");
        jbPLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPLSActionPerformed(evt);
            }
        });

        jbXPFS.setText("XPFS");
        jbXPFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbXPFSActionPerformed(evt);
            }
        });

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jbM3U)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jbPLS)
                .addGap(53, 53, 53)
                .addComponent(jbXPFS)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAceptar)
                        .addGap(79, 79, 79)
                        .addComponent(jbCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jlTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbCancelar))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbM3U)
                    .addComponent(jbPLS)
                    .addComponent(jbXPFS))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbM3UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbM3UActionPerformed
        decision(0);
    }//GEN-LAST:event_jbM3UActionPerformed

    private void jbPLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPLSActionPerformed
        decision(1);
    }//GEN-LAST:event_jbPLSActionPerformed

    private void jbXPFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbXPFSActionPerformed
        decision(2);
    }//GEN-LAST:event_jbXPFSActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        this.haPulsadoAceptar = true;
        this.setVisible(false);
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.haPulsadoAceptar = false;
        this.setVisible(false);
    }//GEN-LAST:event_jbCancelarActionPerformed
    /**
     * Función que recibirá un int dependiendo de que botón ha sido pulsado
     * ocultará los botones y sacará un texto nuevo, preguntando si está seguro
     * de la decisión tomada, y también habrá un botón que aparecerá de aceptar.
     * @param decision -> int (M3U => 0, PLS => 1, XPFS => 2)
     */
    private void decision(int decision){
        jbM3U.setVisible(false);
        jbPLS.setVisible(false);
        jbXPFS.setVisible(false);
        jbAceptar.setVisible(true);
        jbCancelar.setVisible(true);
        switch(decision) {
            case 0 -> {
                jlTexto.setText("Ha seleccionado M3U, ¿Está seguro?");
                this.DECISION = 0;
            }
            case 1 -> {
                jlTexto.setText("Ha seleccionado PLS, ¿Está seguro?");
                this.DECISION = 1;
            }
            case 2 -> {
                jlTexto.setText("Ha seleccionado XPFS, ¿Está seguro?");
                this.DECISION = 2;
            }
        }
    }
    
    public int getDecision(){
        return this.DECISION;
    }
    public boolean getHaPulsadoAceptar(){
        return this.haPulsadoAceptar;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdGuardarPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdGuardarPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdGuardarPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdGuardarPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdGuardarPlaylist dialog = new jdGuardarPlaylist(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbM3U;
    private javax.swing.JButton jbPLS;
    private javax.swing.JButton jbXPFS;
    private javax.swing.JLabel jlTexto;
    // End of variables declaration//GEN-END:variables
}
